apiVersion: v1
kind: Service
metadata:
  name: main-svc
  labels:
    app: main
spec:
  selector:
    app: main
  ports:
    - port: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-deploy-v1
  labels:
    app: main
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main
      version: v1
  template:
    metadata:
      labels:
        app: main
        version: v1
    spec:
      containers:
        - name: main
          image: ddung1203/main:6
          command: ["python",  "main.py"]
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /api/product
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/product
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 2
            timeoutSeconds: 1