apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-queue
  labels:
    app: queue
    version: main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queue
      version: main
  template:
    metadata:
      labels:
        app: queue
        version: main
    spec:
      containers:
        - name: main-queue
          image: ddung1203/main-queue:2
          command: ["python", "consumer.py"]