apiVersion: v1
kind: Service
metadata:
  name: main-svc-np
spec:
  type: NodePort
  selector:
    app: main
  ports:
    - port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: main
  template:
    metadata:
      labels:
        app: main
    spec:
      containers:
        - name: main
          image: ddung1203/main:4
          command: ["python",  "main.py"]
          ports:
            - containerPort: 5000
      initContainers:
        - name: db-init
          image: ddung1203/main:4
          command:
          - "sh"
          - "-c"
          - |
            if [ ! -f /app/init_complete ]; then
              flask --app manager db init
              flask --app manager db migrate
              flask --app manager db upgrade
              touch /app/init_complete
            fi