"""empty message

Revision ID: 1ba7c3696461
Revises: eed56f5ab272
Create Date: 2023-05-17 16:34:03.081739

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1ba7c3696461'
down_revision = 'eed56f5ab272'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_user', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('product_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_index('product_id')
        batch_op.drop_index('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_user', schema=None) as batch_op:
        batch_op.create_index('user_id', ['user_id'], unique=False)
        batch_op.create_index('product_id', ['product_id'], unique=False)
        batch_op.alter_column('product_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
