apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-queue-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-queue
  template:
    metadata:
      labels:
        app: admin-queue
    spec:
      containers:
        - name: admin-queue
          image: ddung1203/admin-queue:1
          command: ["python", "consumer.py"]