apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-queue
  labels:
    app: queue
    version: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queue
      version: admin
  template:
    metadata:
      labels:
        app: queue
        version: admin
    spec:
      containers:
        - name: admin-queue
          image: ddung1203/admin-queue:1
          command: ["python", "consumer.py"]