apiVersion: v1
kind: Service
metadata:
  name: admin-svc-np
spec:
  type: NodePort
  selector:
    app: admin
  ports:
    - port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin
          image: ddung1203/admin:10
          command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
          ports:
            - containerPort: 8000
      initContainers:
        - name: migration
          image: ddung1203/admin:10
          command: ["python", "manage.py", "migrate"]