apiVersion: v1
kind: Service
metadata:
  name: admin-mysql
spec:
  ports:
  - port: 3306
  selector:
    app: admin-mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-mysql
spec:
  selector:
    matchLabels:
      app: admin-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: admin-mysql
    spec:
      containers:
      - image: mysql:8.0.33-debian
        name: admin-mysql
        env:
          # Use secret in real usage
        - name: MYSQL_DATABASE
          value: admin
        - name: MYSQL_PASSWORD
          value: root
        - name: MYSQL_ROOT_PASSWORD
          value: root
        ports:
        - containerPort: 3306
          name: admin-mysql
        volumeMounts:
        - name: admin-mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: admin-mysql-persistent-storage
        persistentVolumeClaim:
          claimName: admin-mysql-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: admin-mysql-pv-claim
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi